-- AlterTable User
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "cpf" TEXT;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "easyDentalPrestadorId" TEXT;

-- AlterTable Patient
ALTER TABLE "Patient" ADD COLUMN IF NOT EXISTS "cpf" TEXT;
ALTER TABLE "Patient" ADD COLUMN IF NOT EXISTS "easyDentalId" TEXT;
ALTER TABLE "Patient" ADD COLUMN IF NOT EXISTS "easyDentalSyncStatus" TEXT DEFAULT 'SINCRONIZADO';
